// ── Demo / Fallback Data ──────────────────────────────────────────────────────
// Used when Supabase is not configured (local dev without DB).
// All images from Unsplash — never 404.

import type { Product, Category } from '@/types';

export const DEMO_CATEGORIES: Category[] = [
  { id: 'cat-veg',    name: 'Farm Fresh Vegetables',   slug: 'farm-fresh',        imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=200&h=200&fit=crop&auto=format', iconUrl: null, parentId: null, sortOrder: 1,  description: null },
  { id: 'cat-fruit',  name: 'Fresh Fruits',             slug: 'fruits',            imageUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=200&h=200&fit=crop&auto=format', iconUrl: null, parentId: null, sortOrder: 2,  description: null },
  { id: 'cat-rice',   name: 'Traditional Rice',         slug: 'traditional-rice',  imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=200&h=200&fit=crop&auto=format', iconUrl: null, parentId: null, sortOrder: 3,  description: null },
  { id: 'cat-oil',    name: 'Cold-Pressed Oils',        slug: 'cold-pressed-oils', imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=200&h=200&fit=crop&auto=format', iconUrl: null, parentId: null, sortOrder: 4,  description: null },
  { id: 'cat-sugar',  name: 'Country Sugar & Jaggery',  slug: 'sugar-jaggery',     imageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=200&h=200&fit=crop&auto=format', iconUrl: null, parentId: null, sortOrder: 5,  description: null },
  { id: 'cat-grain',  name: 'Organic Grains & Pulses',  slug: 'grains-pulses',     imageUrl: 'https://images.unsplash.com/photo-1515942661900-94b3d1972591?w=200&h=200&fit=crop&auto=format', iconUrl: null, parentId: null, sortOrder: 6,  description: null },
  { id: 'cat-dairy',  name: 'Dairy & Ghee',             slug: 'dairy-ghee',        imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200&h=200&fit=crop&auto=format', iconUrl: null, parentId: null, sortOrder: 7,  description: null },
  { id: 'cat-spice',  name: 'Spices & Masala',          slug: 'spices',            imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=200&h=200&fit=crop&auto=format', iconUrl: null, parentId: null, sortOrder: 8,  description: null },
  { id: 'cat-pickle', name: 'Pickles & Chutneys',       slug: 'pickles',           imageUrl: 'https://images.unsplash.com/photo-1563822249366-3efb23b8e0c9?w=200&h=200&fit=crop&auto=format', iconUrl: null, parentId: null, sortOrder: 9,  description: null },
  { id: 'cat-honey',  name: 'Honey & Sweeteners',       slug: 'honey',             imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=200&h=200&fit=crop&auto=format', iconUrl: null, parentId: null, sortOrder: 10, description: null },
  { id: 'cat-org',    name: 'Certified Organic',        slug: 'organic',           imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=200&h=200&fit=crop&auto=format', iconUrl: null, parentId: null, sortOrder: 11, description: null },
  { id: 'cat-trad',   name: 'Traditional Products',     slug: 'traditional',       imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=200&h=200&fit=crop&auto=format', iconUrl: null, parentId: null, sortOrder: 12, description: null },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'p01', name: 'Organic Broccoli', slug: 'organic-broccoli-500g',
    description: 'Farm-fresh broccoli grown without chemicals. Rich in vitamins C and K. Harvested daily from our partner farms in Ooty.',
    imageUrls: ['https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-veg', categoryName: 'Farm Fresh Vegetables', categorySlug: 'farm-fresh',
    brandId: 'brand-ff', brandName: 'Farmers Factory', sku: 'FF-VEG-001',
    mrp: 65, price: 55, unit: '500g', tags: ['vegetables','organic','healthy'],
    isFeatured: true, inStock: true, averageRating: 4.6, reviewCount: 312,
  },
  {
    id: 'p02', name: 'Country Tomatoes', slug: 'country-tomatoes-1kg',
    description: 'Vine-ripened country tomatoes sourced directly from Karnataka farms. Perfect for gravies, soups, and salads.',
    imageUrls: ['https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-veg', categoryName: 'Farm Fresh Vegetables', categorySlug: 'farm-fresh',
    brandId: 'brand-ff', brandName: 'Farmers Factory', sku: 'FF-VEG-002',
    mrp: 40, price: 32, unit: '1kg', tags: ['vegetables','fresh'],
    isFeatured: false, inStock: true, averageRating: 4.3, reviewCount: 189,
  },
  {
    id: 'p03', name: 'Baby Spinach', slug: 'baby-spinach-250g',
    description: 'Tender baby spinach leaves, freshly harvested. Zero pesticides. Perfect for salads, smoothies, and stir-fries.',
    imageUrls: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-veg', categoryName: 'Farm Fresh Vegetables', categorySlug: 'farm-fresh',
    brandId: 'brand-ff', brandName: 'Farmers Factory', sku: 'FF-VEG-003',
    mrp: 45, price: 38, unit: '250g', tags: ['vegetables','leafy','organic'],
    isFeatured: true, inStock: true, averageRating: 4.7, reviewCount: 445,
  },
  {
    id: 'p04', name: 'Sweet Corn', slug: 'sweet-corn-2-cobs',
    description: 'Fresh sweet corn, plucked at peak sweetness. Great for boiling, grilling, and salads.',
    imageUrls: ['https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-veg', categoryName: 'Farm Fresh Vegetables', categorySlug: 'farm-fresh',
    brandId: 'brand-ff', brandName: 'Farmers Factory', sku: 'FF-VEG-004',
    mrp: 30, price: 25, unit: '2 cobs', tags: ['vegetables','fresh'],
    isFeatured: false, inStock: true, averageRating: 4.4, reviewCount: 267,
  },
  {
    id: 'p05', name: 'Alphonso Mangoes', slug: 'alphonso-mangoes-1kg',
    description: 'The king of mangoes — Alphonso from Ratnagiri. Naturally ripened, juicy and sweet.',
    imageUrls: ['https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-fruit', categoryName: 'Fresh Fruits', categorySlug: 'fruits',
    brandId: 'brand-ff', brandName: 'Farmers Factory', sku: 'FF-FRUIT-001',
    mrp: 280, price: 240, unit: '1kg (5-6 pcs)', tags: ['fruits','mango','seasonal'],
    isFeatured: true, inStock: true, averageRating: 4.9, reviewCount: 876,
  },
  {
    id: 'p06', name: 'Red Apples', slug: 'red-apples-1kg',
    description: 'Crispy Himachali red apples, freshly sourced from orchards. High in fibre and natural antioxidants.',
    imageUrls: ['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-fruit', categoryName: 'Fresh Fruits', categorySlug: 'fruits',
    brandId: 'brand-ff', brandName: 'Farmers Factory', sku: 'FF-FRUIT-002',
    mrp: 180, price: 155, unit: '1kg', tags: ['fruits','apple','healthy'],
    isFeatured: false, inStock: true, averageRating: 4.5, reviewCount: 534,
  },
  {
    id: 'p07', name: 'Fresh Coconut', slug: 'fresh-coconut-each',
    description: 'Tender green coconut with refreshing natural water. Each coconut yields 200-300ml of natural electrolyte drink.',
    imageUrls: ['https://images.unsplash.com/photo-1581367736519-0a48c31da7c5?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-fruit', categoryName: 'Fresh Fruits', categorySlug: 'fruits',
    brandId: 'brand-ff', brandName: 'Farmers Factory', sku: 'FF-FRUIT-003',
    mrp: 45, price: 38, unit: 'Each', tags: ['fruits','coconut','healthy'],
    isFeatured: true, inStock: true, averageRating: 4.6, reviewCount: 423,
  },
  {
    id: 'p08', name: 'Seeraga Samba Rice', slug: 'seeraga-samba-rice-5kg',
    description: 'Heritage Seeraga Samba rice from Tamil Nadu. Fragrant, slender grain — ideal for biryani and pulao.',
    imageUrls: ['https://images.unsplash.com/photo-1536304993881-ff86e0c9c5e9?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-rice', categoryName: 'Traditional Rice', categorySlug: 'traditional-rice',
    brandId: 'brand-valluvam', brandName: 'Valluvam Products', sku: 'VL-RICE-001',
    mrp: 650, price: 590, unit: '5kg', tags: ['rice','traditional','biryani'],
    isFeatured: true, inStock: true, averageRating: 4.8, reviewCount: 721,
  },
  {
    id: 'p09', name: 'Ponni Boiled Rice', slug: 'ponni-boiled-rice-5kg',
    description: 'Classic Ponni Boiled Rice — the staple of Tamil Nadu homes. Double-boiled for better nutrition.',
    imageUrls: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-rice', categoryName: 'Traditional Rice', categorySlug: 'traditional-rice',
    brandId: 'brand-valluvam', brandName: 'Valluvam Products', sku: 'VL-RICE-002',
    mrp: 340, price: 310, unit: '5kg', tags: ['rice','traditional'],
    isFeatured: false, inStock: true, averageRating: 4.5, reviewCount: 398,
  },
  {
    id: 'p10', name: 'Cold-Pressed Gingelly Oil', slug: 'cold-pressed-gingelly-oil-1l',
    description: 'Pure cold-pressed sesame oil from traditional wooden churner. Retains all nutrients and authentic flavour.',
    imageUrls: ['https://qwiumswrbddwmlraktvy.supabase.co/storage/v1/object/public/app-images/oils/sesame-1L.jpg'],
    blurDataUrls: [], categoryId: 'cat-oil', categoryName: 'Cold-Pressed Oils', categorySlug: 'cold-pressed-oils',
    brandId: 'brand-valluvam', brandName: 'Valluvam Products', sku: 'VL-OIL-001',
    mrp: 420, price: 380, unit: '1 Litre', tags: ['oil','cold-pressed','sesame'],
    isFeatured: true, inStock: true, averageRating: 4.9, reviewCount: 1243,
  },
  {
    id: 'p11', name: 'Cold-Pressed Coconut Oil', slug: 'cold-pressed-coconut-oil-500ml',
    description: 'Virgin cold-pressed coconut oil — chemical-free, first-press extraction.',
    imageUrls: ['https://qwiumswrbddwmlraktvy.supabase.co/storage/v1/object/public/app-images/oils/coconutoil250.jpg'],
    blurDataUrls: [], categoryId: 'cat-oil', categoryName: 'Cold-Pressed Oils', categorySlug: 'cold-pressed-oils',
    brandId: 'brand-valluvam', brandName: 'Valluvam Products', sku: 'VL-OIL-002',
    mrp: 320, price: 285, unit: '500ml', tags: ['oil','cold-pressed','coconut'],
    isFeatured: true, inStock: true, averageRating: 4.8, reviewCount: 987,
  },
  {
    id: 'p12', name: 'Country Jaggery (Vellam)', slug: 'country-jaggery-1kg',
    description: 'Traditional palm jaggery from Villupuram. Made using age-old methods. Unprocessed, chemical-free.',
    imageUrls: ['https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-sugar', categoryName: 'Country Sugar & Jaggery', categorySlug: 'sugar-jaggery',
    brandId: 'brand-valluvam', brandName: 'Valluvam Products', sku: 'VL-SUGAR-001',
    mrp: 180, price: 155, unit: '1kg', tags: ['jaggery','natural','unprocessed'],
    isFeatured: true, inStock: true, averageRating: 4.7, reviewCount: 634,
  },
  {
    id: 'p13', name: 'Palm Sugar (Panangkarkandu)', slug: 'palm-sugar-500g',
    description: 'Authentic panangkarkandu from Tirunelveli. Natural sweetener with a rich caramel flavour.',
    imageUrls: ['https://images.unsplash.com/photo-1516684732162-798a0062be99?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-sugar', categoryName: 'Country Sugar & Jaggery', categorySlug: 'sugar-jaggery',
    brandId: 'brand-valluvam', brandName: 'Valluvam Products', sku: 'VL-SUGAR-002',
    mrp: 220, price: 195, unit: '500g', tags: ['sugar','palm','natural'],
    isFeatured: false, inStock: true, averageRating: 4.6, reviewCount: 312,
  },
  {
    id: 'p14', name: 'Organic Masoor Dal', slug: 'organic-masoor-dal-1kg',
    description: 'Organically grown red lentils from certified farms. High protein. Cooks in under 20 minutes.',
    imageUrls: ['https://images.unsplash.com/photo-1515942661900-94b3d1972591?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-grain', categoryName: 'Organic Grains & Pulses', categorySlug: 'grains-pulses',
    brandId: 'brand-ff', brandName: 'Farmers Factory', sku: 'FF-GRAIN-001',
    mrp: 140, price: 120, unit: '1kg', tags: ['pulses','organic','protein'],
    isFeatured: false, inStock: true, averageRating: 4.4, reviewCount: 289,
  },
  {
    id: 'p15', name: 'Organic Ragi Flour', slug: 'organic-ragi-flour-1kg',
    description: 'Stone-ground organic finger millet flour. Rich in calcium, iron and fibre. Perfect for dosas and rotis.',
    imageUrls: ['https://images.unsplash.com/photo-1589927986089-35812378533e?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-grain', categoryName: 'Organic Grains & Pulses', categorySlug: 'grains-pulses',
    brandId: 'brand-ff', brandName: 'Farmers Factory', sku: 'FF-GRAIN-002',
    mrp: 130, price: 110, unit: '1kg', tags: ['grain','ragi','organic','millets'],
    isFeatured: true, inStock: true, averageRating: 4.7, reviewCount: 521,
  },
  {
    id: 'p16', name: 'Pure Cow Ghee', slug: 'pure-cow-ghee-500ml',
    description: 'Pure cow ghee made with traditional bilona method. Rich in butyric acid and natural vitamins.',
    imageUrls: ['https://qwiumswrbddwmlraktvy.supabase.co/storage/v1/object/public/app-images/valluvam/Ghee250.jpg'],
    blurDataUrls: [], categoryId: 'cat-dairy', categoryName: 'Dairy & Ghee', categorySlug: 'dairy-ghee',
    brandId: 'brand-valluvam', brandName: 'Valluvam Products', sku: 'FF-DAIRY-001',
    mrp: 670, price: 570, unit: '500g', tags: ['ghee','cow','traditional'],
    isFeatured: true, inStock: true, averageRating: 4.9, reviewCount: 1567,
  },
  {
    id: 'p17', name: 'Fresh Curd (Thayir)', slug: 'fresh-curd-500g',
    description: 'Made from fresh full-cream milk, set overnight. Thick and creamy. No preservatives.',
    imageUrls: ['https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-dairy', categoryName: 'Dairy & Ghee', categorySlug: 'dairy-ghee',
    brandId: 'brand-ff', brandName: 'Farmers Factory', sku: 'FF-DAIRY-002',
    mrp: 55, price: 50, unit: '500g', tags: ['dairy','curd','fresh'],
    isFeatured: false, inStock: true, averageRating: 4.5, reviewCount: 438,
  },
  {
    id: 'p18', name: 'Chettinad Masala Powder', slug: 'chettinad-masala-200g',
    description: 'Authentic Chettinad masala hand-ground with 18 spices. No artificial colour or preservatives.',
    imageUrls: ['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-spice', categoryName: 'Spices & Masala', categorySlug: 'spices',
    brandId: 'brand-valluvam', brandName: 'Valluvam Products', sku: 'VL-SPICE-001',
    mrp: 180, price: 155, unit: '200g', tags: ['spice','masala','chettinad'],
    isFeatured: true, inStock: true, averageRating: 4.8, reviewCount: 892,
  },
  {
    id: 'p19', name: 'Raw Forest Honey', slug: 'raw-forest-honey-500g',
    description: 'Unprocessed raw honey from wild bee hives in the Nilgiris forest. Never heated, retains all enzymes.',
    imageUrls: ['https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-honey', categoryName: 'Honey & Sweeteners', categorySlug: 'honey',
    brandId: 'brand-ff', brandName: 'Farmers Factory', sku: 'FF-HONEY-001',
    mrp: 420, price: 380, unit: '500g', tags: ['honey','raw','natural','forest'],
    isFeatured: true, inStock: true, averageRating: 4.9, reviewCount: 1123,
  },
  {
    id: 'p20', name: 'Mango Pickle (Avakaya)', slug: 'homestyle-mango-pickle-400g',
    description: "Traditional Telugu-style raw mango pickle made with first-press gingelly oil. Grandma's recipe.",
    imageUrls: ['https://images.unsplash.com/photo-1589135716831-73e74f9e89c5?w=400&h=400&fit=crop&auto=format'],
    blurDataUrls: [], categoryId: 'cat-pickle', categoryName: 'Pickles & Chutneys', categorySlug: 'pickles',
    brandId: 'brand-valluvam', brandName: 'Valluvam Products', sku: 'VL-PICKLE-001',
    mrp: 220, price: 190, unit: '400g', tags: ['pickle','mango','traditional'],
    isFeatured: true, inStock: true, averageRating: 4.7, reviewCount: 645,
  },
];
