export const VEGETABLE_CATEGORY_SLUG = 'vegetables';
export const VEGETABLE_IMAGE_BASE = '/images/vegtables';

export const VEGETABLE_PRODUCTS = [
  { name: 'Ash Gourd', unit: '10 Kg', price: 130, imageFile: 'AshGourd.jfif' },
  { name: 'Ash Gourd', unit: '3 Kg', price: 45, imageFile: 'AshGourd.jfif' },
  { name: 'Avarakkai', unit: '1 Kg', price: 60, imageFile: 'Avarakkai.jfif' },
  { name: 'Baby Corn', unit: '1 Box', price: 35, imageFile: 'BabyCorn.jfif' },
  { name: 'Baby Potato', unit: '1 Kg', price: 40, imageFile: 'BabyPotato.jfif' },
  { name: 'Baji Chilli', unit: '1 Kg', price: 75, imageFile: 'BajiChilli.jfif' },
  { name: 'Banana Flower', unit: '1 Pc', price: 30, imageFile: 'BananaFlower.jfif' },
  { name: 'Banana Stem', unit: '1 Pc', price: 12, imageFile: 'BananaStem.jfif' },
  { name: 'Beans', unit: '1 Kg', price: 135, imageFile: 'Beans.jfif' },
  { name: 'Bitter Gourd', unit: '1 Kg', price: 70, imageFile: 'bitter-gourd.jpg' },
  { name: 'Bitter Gourd Paneer', unit: '1 Kg', price: 70, imageFile: 'bitter-gourd.jpg' },
  { name: 'Bottle Gourd', unit: '1 Kg', price: 45, imageFile: 'BottleGourd.jfif' },
  { name: 'Brinjal Eggplant', unit: '1 Kg', price: 70, imageFile: 'BrinjalEggplant.jfif' },
  { name: 'Brinjal Ujala', unit: '1 Kg', price: 52, imageFile: 'Brinjal.jfif' },
  { name: 'Brinjal Ujala', unit: '3 Kg', price: 150, imageFile: 'Brinjal.jfif' },
  { name: 'Brinjal Vari', unit: '1 Kg', price: 40, imageFile: 'BrinjalVari.jfif' },
  { name: 'Broccoli', unit: '1 Kg', price: 190, imageFile: 'Broccoli.jfif' },
  { name: 'Coriander Leaves', unit: 'Bunch', price: 8, imageFile: 'CorianderLeaves.jfif' },
  { name: 'Mint Leaves', unit: 'Bunch', price: 7, imageFile: 'MintLeaves.jfif' },
  { name: 'Spring Onion', unit: 'Bunch', price: 17, imageFile: 'SpringOnion.jfif' },
  { name: 'Button Mushroom', unit: '1 Box', price: 48, imageFile: 'ButtonMushrooms.jfif' },
  { name: 'Cabbage', unit: '1 Kg', price: 22, imageFile: 'Cabbage.jfif' },
  { name: 'Cabbage', unit: '10 Kg', price: 190, imageFile: 'Cabbage.jfif' },
  { name: 'Purple Cabbage', unit: '1 Kg', price: 80, imageFile: 'PurpleCabbage.jfif' },
  { name: 'Capsicum Green', unit: '1 Kg', price: 55, imageFile: 'CapsicumGreen.jfif' },
  { name: 'Cauliflower', unit: '1 Pc', price: 30, imageFile: 'Cauliflower.jfif' },
  { name: 'Channa Brown Sprouts', unit: '200 gm', price: 25, imageFile: 'MixedSprouts.jfif' },
  { name: 'Chow Chow', unit: '1 Kg', price: 40, imageFile: 'ChowChow.jfif' },
  { name: 'Cluster Beans', unit: '3 Kg', price: 195, imageFile: 'ClusterBeans.jfif' },
  { name: 'Coconut', unit: '1 Kg', price: 58, imageFile: 'Coconut.jfif' },
  { name: 'Coconut', unit: '10 Kg', price: 540, imageFile: 'Coconut.jfif' },
  { name: 'Coconut', unit: '5 Kg', price: 280, imageFile: 'Coconut.jfif' },
  { name: 'Cucumber Indian', unit: '1 Kg', price: 40, imageFile: 'Cucumber.jfif' },
  { name: 'Curry Leaves', unit: '1 Kg', price: 60, imageFile: 'CurryLeaves.jfif' },
  { name: 'Drumstick', unit: '1 Kg', price: 45, imageFile: 'drumstick.jpg' },
  { name: 'Drumstick', unit: '3 Kg', price: 120, imageFile: 'drumstick.jpg' },
  { name: 'Garlic Local', unit: '1 Kg', price: 200, imageFile: 'Garlic.jfif' },
  { name: 'Garlic Local', unit: '3 Kg', price: 540, imageFile: 'Garlic.jfif' },
  { name: 'Ginger', unit: '1 Kg', price: 110, imageFile: 'Ginger.jfif' },
  { name: 'Ginger', unit: '3 Kg', price: 315, imageFile: 'Ginger.jfif' },
  { name: 'Green Chilli', unit: '1 Kg', price: 55, imageFile: 'Greenchili.jfif' },
  { name: 'Green Chilli', unit: '3 Kg', price: 150, imageFile: 'Greenchili.jfif' },
  { name: 'Green Peas', unit: '1 Kg', price: 180, imageFile: 'GreenPeas.jfif' },
  { name: 'Karunaikizhangu', unit: '1 Kg', price: 50, imageFile: 'Karunaikizhangu.jfif' },
  { name: 'Karunaikizhangu', unit: '3 Kg', price: 135, imageFile: 'Karunaikizhangu.jfif' },
  { name: 'Nookal', unit: '1 Kg', price: 50, imageFile: 'nookal.webp' },
  { name: 'Kovaikkai', unit: '1 Kg', price: 48, imageFile: 'Kovaikkai.jfif' },
  { name: 'Ladies Finger', unit: '1 Kg', price: 55, imageFile: 'LadiesFinger.jfif' },
  { name: 'Ladies Finger', unit: '3 Kg', price: 156, imageFile: 'LadiesFinger.jfif' },
  { name: 'Lemon', unit: '1 Kg', price: 230, imageFile: 'lemon.jfif' },
  { name: 'Lemon', unit: '3 Kg', price: 675, imageFile: 'lemon.jfif' },
  { name: 'Maravalli Kilangu', unit: '1 Kg', price: 50, imageFile: 'MaravalliKilangu.jfif' },
  { name: 'Mixed Sprouts', unit: '200 gm', price: 25, imageFile: 'MixedSprouts.jfif' },
  { name: 'Moong Green Sprouts', unit: '200 gm', price: 25, imageFile: 'MoongGreenSprouts.jfif' },
  { name: 'Onion Nasik', unit: '50 Kg', price: 1150, imageFile: 'OnionNasik.jfif' },
  { name: 'Onion Nasik Medium', unit: '1 Kg', price: 27, imageFile: 'OnionNasik.jfif' },
  { name: 'Onion Nasik Medium', unit: '25 Kg', price: 625, imageFile: 'OnionNasik.jfif' },
  { name: 'Onion Pink Big', unit: '25 Kg', price: 700, imageFile: 'onionbig.jfif' },
  { name: 'Onion Pink Big', unit: '50 Kg', price: 1300, imageFile: 'onionbig.jfif' },
  { name: 'Onion Small', unit: '1 Kg', price: 65, imageFile: 'Onionred.jfif' },
  { name: 'Onion Small', unit: '4 Kg', price: 240, imageFile: 'Onionred.jfif' },
  { name: 'Ooty Beetroot', unit: '1 Kg', price: 50, imageFile: 'beetroot.jfif' },
  { name: 'Ooty Carrot', unit: '1 Kg', price: 50, imageFile: 'ooty-carrot.jpg' },
  { name: 'Organic Capsicum Red', unit: '1 Kg', price: 280, imageFile: 'CapsicumRed.jfif' },
  { name: 'Organic Capsicum Yellow', unit: '1 Kg', price: 280, imageFile: 'CapsicumYellow.jfif' },
  { name: 'Organic Cucumber', unit: '1 Kg', price: 42, imageFile: 'Cucumber.jfif' },
  { name: 'Potato Hassan Medium', unit: '10 Kg', price: 240, imageFile: 'potato.jfif' },
  { name: 'Potato Hassan Medium', unit: '1 Kg', price: 26, imageFile: 'potato.jfif' },
  { name: 'Potato Hassan Medium', unit: '40 Kg', price: 880, imageFile: 'potato.jfif' },
  { name: 'Sweet Potato', unit: '1 Kg', price: 46, imageFile: 'sweetpotato.jfif' },
  { name: 'Pumpkin Yellow', unit: '10 Kg', price: 250, imageFile: 'PumpkinYellow.jfif' },
  { name: 'Pumpkin Yellow', unit: '5 Kg', price: 140, imageFile: 'PumpkinYellow.jfif' },
  { name: 'Radish', unit: '1 Kg', price: 40, imageFile: 'Radish.jfif' },
  { name: 'Radish', unit: '3 Kg', price: 105, imageFile: 'Radish.jfif' },
  { name: 'Raw Banana', unit: 'Per Piece', price: 12, imageFile: 'RawBanana.jfif' },
  { name: 'Raw Mango', unit: '1 Kg', price: 40, imageFile: 'RawMango.jfif' },
  { name: 'Ridge Gourd', unit: '1 Kg', price: 70, imageFile: 'Ridgegourd.jfif' },
  { name: 'Seppankizhangu / Arvi', unit: '3 Kg', price: 156, imageFile: 'Seppankizhangu.jfif' },
  { name: 'Seppankizhangu / Arvi', unit: '1 Kg', price: 55, imageFile: 'Seppankizhangu.jfif' },
  { name: 'Snake Gourd', unit: '1 Kg', price: 60, imageFile: 'SnakeGourd.jfif' },
  { name: 'Sweet Corn', unit: '1 Kg', price: 30, imageFile: 'sweetcorn.jfif' },
  { name: 'Tomato Bangalore', unit: '1 Kg', price: 60, imageFile: 'TomatoBangalore.jfif' },
  { name: 'Tomato Country Ripped', unit: '14 Kg', price: 672, imageFile: 'TomatoCountry.jfif' },
  { name: 'Tomato Country Ripped', unit: '1 Kg', price: 50, imageFile: 'TomatoCountry.jfif' },
  { name: 'Tomato Country Ripped', unit: '25 Kg', price: 1150, imageFile: 'TomatoCountry.jfif' },
  { name: 'Zucchini Green', unit: '1 Kg', price: 150, imageFile: 'ZucchiniGreen.jfif' },
  { name: 'Zucchini Yellow', unit: '1 Kg', price: 150, imageFile: 'ZucchiniYellow.jfif' },
] as const;

export function vegetableSlug(name: string, unit: string) {
  return `${name}-${unit}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export function vegetableImage(imageFile: string) {
  return `${VEGETABLE_IMAGE_BASE}/${encodeURIComponent(imageFile)}`;
}
